Repository DD2480-GROUP-2/DD2480-CI, pull requests merged in 2023-02, with the labels that each got.

#29 (feat) #10 Add response to github API
  pom.xml
  src/main/java/org/Group2/ContinuousIntegrationServer.java
Labels: enhancement

#31 (feat) #28 Added method to parse branch name of a request
  src/main/java/org/Group2/ContinuousIntegrationServer.java
  src/test/java/ContinousIntegrationServerTests.java
Labels: Feature

#45 (fix) #43 add https instead of ssh
  src/main/java/org/Group2/ContinuousIntegrationServer.java
  src/test/java/ContinousIntegrationServerTests.java
Labels: bug

#44 (feat) #32 Implemented maven test function
  src/main/java/org/Group2/ContinuousIntegrationServer.java
  src/test/java/ContinousIntegrationServerTests.java
  testBuilds/testFailTest/pom.xml
  testBuilds/testFailTest/src/main/java/Group2TestFailTest/CMV.java
  testBuilds/testFailTest/src/main/java/Group2TestFailTest/DECIDE.java
  testBuilds/testFailTest/src/main/java/Group2TestFailTest/Input.java
  testBuilds/testFailTest/src/test/java/Tests.java
Labels: Feature

#39 (feat) #38 Add if-statement for request header
  src/main/java/org/Group2/ContinuousIntegrationServer.java
Labels: enhancement, Feature

#46 (feat) #33 Finish integration
  src/main/java/org/Group2/ContinuousIntegrationServer.java
Labels: Feature

#49 (feat) #48 Add execute prop to pom.xml
  pom.xml
Labels: Feature

#53 (feat) #52 Implemented a create log function
  builds/test.txt
  src/main/java/org/Group2/ContinuousIntegrationServer.java
  src/test/java/ContinousIntegrationServerTests.java
Labels: Feature

#55 (feat) #54 Added functionality for mvn test to write logs
  src/main/java/org/Group2/ContinuousIntegrationServer.java
  src/test/java/ContinousIntegrationServerTests.java
Labels: Feature

#57 56 (feat) #56 implement fetching build logs
  README.md
  builds/7105911c48245af0570abefdd487f781fde44869.log
  builds/7e3ffdb757bfe2185b58365cac57e68df82f2ad2.log
  builds/a2acc2839b7a5faa264fa317fdbe83134f314ca1.log
  src/main/java/org/Group2/ContinuousIntegrationServer.java
Labels: Feature

#60 (doc) #36 readme statement of contributions
  README.md
Labels: documentation

#62 (feat) #61 Added negative test for compile function
  src/test/java/ContinousIntegrationServerTests.java
  testBuilds/testFailCompile/pom.xml
  testBuilds/testFailCompile/src/main/java/Group2compileTest/CMV.java
  testBuilds/testFailCompile/src/main/java/Group2compileTest/DECIDE.java
  testBuilds/testFailCompile/src/main/java/Group2compileTest/Input.java
  testBuilds/testFailCompile/src/test/java/Tests.java
Labels: Feature
